### ISSUE TITLE
Noto Khmer Sans UI: cannot use with IE 11 and Notepad on Windows 7

### ISSUE THREAD

**Issue by jungshik** [notofonts/khmer#1]
- How to reproduce 
  1. Go to http://jungshik.github.io/noto/khmer.html in IE 11 on Windows 7
- What's expected
  Two lines of Khmer text (regular and bold) as seen in Chrome and Firefox
- Actual 
  Khmer characters are shown briefly (a fraction of a second) on loading before they disappear. 
- Additional information 
  - The web page uses hinted Noto Sans Khmer UI (ttf) 1.03 (the latest) as a web font 
  - When installing the fonts locally on Windows, I didn't get any complaint from Windows. 
  - However, when I set the font to 'Noto Sans Khmer UI' and type Khmer characters, I got 'tofu'. 
  - I also tried the previous version (1.02) and the result is the same.  (1.03 should work better with U+0000 and U+000D in cmap than 1.02). 
  - Wordpad on Windows 7 works fine
  - IE 10, IE 11 on Win 8 work fine
  - IE 11 and Edge on Win 8 work fine, too.  

/cc @dougfelt 

BTW, this was spun off from an internal bug ( 28800134 ).

**Comment by SKing-2003** [comment]
Neither Internet Explorer nor Windows 7 are supported any more.
