### ISSUE TITLE
Baseline of Noto Sans Khmer UI variable font is not aligned with Latin script

### ISSUE THREAD

**Issue by TidharC** [notofonts/khmer#2]
SUMMARY

With Noto Sans Khmer UI variable font, the Khmer baseline is rendered higher that the Latin script baseline.

REPRODUCTION STEPS

0.  Install the appropriate font and modified fonts.xml file, then reboot.
1.  Navigate through system settings, looking for lines with a mix of Khmer and Latin script (e.g. developer options, network connectivity etc.)

OBSERVED RESULTS

Khmer baseline is higher than Latin baseline (see screenshots).

EXPECTED RESULTS

Same baseline for Khmer and Latin script.

ADDITIONAL INFORMATION

Font name: NotoSansKhmerUI-GX.ttf
Version: 1.900

Platform: Android

![khmerbaseline1](https://cloud.githubusercontent.com/assets/16353803/23083241/aae78e54-f511-11e6-9daf-0f5401cdf0ca.png)

![khmerbaseline2](https://cloud.githubusercontent.com/assets/16353803/23083247/b2b57d6c-f511-11e6-9a0b-25e599c5a254.png)

**Comment by simoncozens** [comment]
The Khmer UI font is admittedly a design compromise, and arguably an unfortunate one, but that *is* the point of the UI fonts; it is a compromise and things get squished into metrics that ideally they shouldn't have. I don't believe that the fix here is to juggle more things around, but to deprecate the concept of UI fonts and make the application layout work better for tall and deep scripts. That's what we have proposed to the Android team, and we are not planning to make any interim changes to the UI families other than obvious bug fixes.
