### ISSUE TITLE
Khmer Qa-Triisap-Vowel Sign II `អ៊ី` shaping in Noto Sans Khmer VF vs. Noto Sans Khmer UI

### ISSUE THREAD

**Issue by chrissimpkins** [notofonts/khmer#26]
A team reported a discrepancy in the Noto Sans Khmer UI vs. non-UI build shaping of `អ៊ី`.

<img width="1760" alt="5C93py6k6fKNyth" src="https://user-images.githubusercontent.com/4249591/185031338-9f2be0eb-a2e3-4647-a90d-50791d461d86.png">

The reporting team feels that the bottom (Noto Sans Khmer VF) form is the correct approach to U+17CA Khmer sign triisap shaping.  Do we know? And should the UI and non-UI build forms be the same?

FWIW, I see the top form in the text content as I type this issue report in the GitHub UI on macOS + Chrome:

![4ThoUKKdYukFfeX](https://user-images.githubusercontent.com/4249591/185032558-a3caad9e-e838-4c84-b847-dd8ae6ec605b.png)

**Comment by simoncozens** [comment]
I think the team must have their hands on an old version. In latest releases of Noto Sans Khmer UI from [here](https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf/NotoSansKhmerUI), the shaping is the same (new form with triisap below). Where did *you* get the font from?

**Comment by chrissimpkins** [comment]
> Where did you get the font file from?

[The Android distribution](https://github.com/rsheeter/android_fonts/blob/master/api_level/31/NotoSansKhmerUI-Regular.ttf)

**Comment by chrissimpkins** [comment]
> I think the team must have their hands on an old version. In latest releases of Noto Sans Khmer UI from [here](https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf/NotoSansKhmerUI) (and development builds [here](https://notofonts.github.io/khmer/)), the shaping is the same (new form with triisap below).

We may only need to push the latest update to them then.  Does the new Khmer UI include Latin?

**Comment by chrissimpkins** [comment]
I shared the latest builds with the team.  Will close this as fixed and reopen if there are additional related requests.
