### ISSUE TITLE
Ascent and descent problems in Sans and Serif document fonts

### ISSUE THREAD

**Issue by Kanjilearner817** [notofonts/khmer#28]
According to FontForge, Noto Sans Khmer and Noto Serif Khmer (non-UI) have an ascent of 800 and a descent of 200, which makes for legibility issues. Meanwhile, Khmer OS Battambang has an ascent of 1638 and a descent of 410, granting much more clearance.

### Font 
  > NotoSerifKhmer-Regular.otf, NotoSansKhmer-Regular.otf, KhmerOSbattambang.ttf

### Where the font came from, and when
  > Site: https://github.com/notofonts/khmer/releases/tag/NotoSerifKhmer-v2.003
  > Date: 2023-05-19

  > Site: https://github.com/notofonts/khmer/releases/tag/NotoSansKhmer-v2.003
  > Date: 2023-05-19

  > Site: https://github.com/wikimedia/mediawiki-extensions-UniversalLanguageSelector/tree/master/data/fontrepo/fonts/KhmerOSbattambang
  > Date: 2022-04-16

### Font Version
  > 2.003 for both Noto fonts in question
  > 1.10 2007 for Khmer OS Battambang

### OS name and version
  > Windows 11 Home 22H2

### Application name and version
  > LibreOffice Writer (LibreOffice 7.5.3.2 [X86_64])

### Screenshot
Noto Sans Khmer
![Screenshot 2023-05-22 134432](https://github.com/notofonts/khmer/assets/13095930/ab54e3ab-d5d8-4561-b617-b80ded0f481b)

Noto Serif Khmer
![Screenshot 2023-05-22 134256](https://github.com/notofonts/khmer/assets/13095930/39150caa-bdd3-4828-977b-298f1099ddd4)

Khmer OS Battambang
![Screenshot 2023-05-22 134320](https://github.com/notofonts/khmer/assets/13095930/d5d3ea1d-8ab0-4849-b59e-be2dacd03f05)

**Comment by simoncozens** [comment]
>  Noto Sans Khmer and Noto Serif Khmer (non-UI) have an ascent of 800 and a descent of 200

I'm not sure this is right: typoAscender/hheaAscender/winAscent are all 1069, and typoDescender/winDescent/hheaDescender is 293. These are set according to the Google Fonts [vertical metrics specification](https://googlefonts.github.io/gf-guide/metrics.html) which, although not perfect, is the best compromise we've found.

At any rate, unfortunately changing these values after the font has been fielded is very disruptive, as it would lead to reflow of documents, so we're unlikely to be able to do that.
