### ISSUE TITLE
Noto Sans Khmer UI variable font & phase III static font has minor string truncation problem

### ISSUE THREAD

**Issue by hrhatada** [notofonts/khmer#4]
STEPS TO REPRODUCE 
1. On the device A, replace the Noto Sans Khmer font to Noto Sans Khmer variable font and modify the fonts.xml file 
2. On the device B, replace the Noto Sans Khmer fonts to the phase III Noto Sans Khmer fonts
3. Reboot both devices and compare the UIs

RESULT : 
1. Phase III Noto Sans Khmer font's baseline is shifted slightly up (related to the issue notofonts/khmer#2)
2. Noto Sans Khmer UI variable font has a truncation problem.  See below screenshot.

![image](https://cloud.githubusercontent.com/assets/16353449/24061646/73256a58-0b15-11e7-99ce-1eb4614e497b.png)

**Comment by simoncozens** [comment]
This is basically the same as #2. It's unfortunate but a real fix is with the application. We can't change the vertical metrics of UI fonts.
