### ISSUE TITLE
Khmer Consonant Shifter bugs

### ISSUE THREAD

**Issue by marekjez86** [notofonts/khmer#7]
@sovichet:

This was copied from https://github.com/googlefonts/noto-source/issues/207

The Noto Khmer typefaces are having a shaping bug with the consonant shifter 'KHMER SIGN MUUSIKATOAN' (U+17C9). It happens in this case: Consonant + Consonant Shifter + Vowel Sign AA (17B6) + Nikahit (17C6).

I believe the consonant below is U+1789

![68747470733a2f2f692e696d6775722e636f6d2f577837553471392e706e67](https://user-images.githubusercontent.com/13322623/85949295-c68a8600-b90a-11ea-9ada-9d9e2ce6115f.png)

**Comment by MakaraSok** [comment]
Texts in red font face are not desirable.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/28331388/232990609-a2b7be66-fb2f-4849-9be6-8ceeb3379551.png">

**Comment by simoncozens** [comment]
OK, I am unsure about how to fix this. Are there any situations where the triisap should go below base?

@NorbertLindenberg  do you have a handy UTN for Implementing Khmer? :-)

**Comment by simoncozens** [comment]
I guess the issue here is that the Unicode Standard says:

>  In the presence of other superscript glyphs, both of these signs are usually rendered with the same glyph shape as that of U+17BB khmer vowel sign u

This *is* what is happening in this font, so is TUS wrong?

**Comment by r12a** [comment]
It's not specific enough. Does this help?
https://r12a.github.io/scripts/khmr/km.html#consonant_shift_posn

> The Unicode Standard[8](https://www.unicode.org/versions/Unicode13.0.0/ch16.pdf) gives the impression that both of these diacritics are moved below the consonant any time a vowel appears over that consonant. However, in reality only certain consonants cause this behaviour. The behaviour varies a little by font, but in general ... TRIISAP is lowered for these characters.

**Comment by simoncozens** [comment]
Perfect, thank you.

**Comment by NorbertLindenberg** [comment]
> @NorbertLindenberg do you have a handy UTN for Implementing Khmer? :-)

Not me, and not a UTN yet: https://www.unicode.org/L2/L2022/22290-khmer-encoding.pdf

This document discusses many of the flaws in the Unicode encoding of Khmer, and proposes a new encoding order. It includes a thorough discussion of consonant shifters. It was developed in collaboration with several Khmer government organizations, but has received lukewarm feedback from SAH/UTC:
https://www.unicode.org/L2/L2023/23012-script-adhoc-rept.pdf
https://www.unicode.org/L2/L2023/23083-script-adhoc-rept.pdf
